CREATE DATABASE VETERINARIA

GO

USE VETERINARIA

GO
CREATE TABLE PERSONAS(
CODIGO INT IDENTITY PRIMARY KEY,
NOMBRE VARCHAR(20) NOT NULL,
APELLIDO VARCHAR(30) NOT NULL,
TELEFONO VARCHAR(11),
TIPO_TELEFONO VARCHAR(3),
CORREO VARCHAR(50),
IDENTIFICACION VARCHAR(11),
TIPO_IDENTIFICACION VARCHAR(3),
CONSTRAINT CK_TIPO_TELEFONO CHECK( TIPO_TELEFONO IN ('CEL','TEL') ),
CONSTRAINT CK_TIPO_IDENTIFICACION CHECK (TIPO_IDENTIFICACION IN ('CED','PAS'))
);

GO
CREATE TABLE RAZA(
CODIGO INT IDENTITY PRIMARY KEY,
DESCRIPCION VARCHAR(40) NOT NULL
)

GO
CREATE TABLE TIP_ANIMAL(
CODIGO INT IDENTITY PRIMARY KEY,
DESCRIPCION VARCHAR(40) NOT NULL
);

GO
CREATE TABLE MASCOTAS(
CODIGO INT IDENTITY PRIMARY KEY,
NOMBRE VARCHAR(20) NOT NULL,
COD_TIPO_ANIMAL INT NOT NULL,
COD_RAZA INT NOT NULL,
EDAD int NOT NULL,
PESO DECIMAL(5,2),
SEXO CHAR(1) CONSTRAINT CK_SEXO CHECK(SEXO IN ('M','F')),
CONSTRAINT CK_TIP_AN FOREIGN KEY (COD_TIPO_ANIMAL) REFERENCES TIP_ANIMAL(CODIGO),
CONSTRAINT CK_RAZA FOREIGN KEY (COD_RAZA) REFERENCES RAZA(CODIGO),
);

GO
CREATE TABLE PROCEDIMIENTOS(
CODIGO INT IDENTITY PRIMARY KEY,
DESCRIPCION VARCHAR(100) NOT NULL,
PRECIO DECIMAL(5,2) NOT NULL
)

GO
CREATE TABLE CITA(
CODIGO INT IDENTITY PRIMARY KEY,
FEC_TRA DATETIME NOT NULL,
--FEC_CITA DATETIME NOT NULL,
FEC_FUTURA DATETIME NOT NULL,
MASCOTA_CODIGO INT NOT NULL,
PERSONA_CODIGO INT NOT NULL,
COD_PROCEDIMIENTO INT NOT NULL,
CONSTRAINT FK_MASCOTA FOREIGN KEY (MASCOTA_CODIGO) REFERENCES MASCOTAS(CODIGO),
CONSTRAINT FK_PERSONA FOREIGN KEY (PERSONA_CODIGO) REFERENCES PERSONAS(CODIGO),
CONSTRAINT FK_PROCEDIMIENTO FOREIGN KEY (COD_PROCEDIMIENTO) REFERENCES PROCEDIMIENTOS(CODIGO)
);

CREATE TABLE LOGIN(
CODIGO INT IDENTITY PRIMARY KEY,
USUARIO VARCHAR(50) NOT NULL,
CONTRASENA VARCHAR(50) NOT NULL,
NOMBRES VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(50) NOT NULL,
CORREO VARCHAR(100) NOT NULL
)


/*CREATE TABLE MASCOTA_PERSONA(
CODIGO INT IDENTITY PRIMARY KEY,
CODIGO_PERSONA INT FOREIGN KEY (CODIGO_PERSONA) REFERENCES PERSONAS(CODIGO),
CODIGO_MASCOTA INT FOREIGN KEY (CODIGO_MASCOTA) REFERENCES MASCOTAS(CODIGO)
);*/